### ISSUE TITLE
Burp Suite Pro 2023.1 失效了

### ISSUE THREAD

**Issue by xcxmiku** [googleweb/loader#2]
下载链接 https://portswigger.net/burp/releases

**Comment by googleweb** [comment]
我已经收到您的信件!

**Comment by googleweb** [comment]
一种方式失效了。
使用[loader-small.zip](https://github.com/googleweb/loader/releases/download/1.0.4/loader-small.zip)这个试试。
或者删除config目录下loader.conf。
或者把loader.conf里1改成2。
